import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import AppLayout from '../components/AppLayout'
import { colors } from '../styles/theme'
import Button from '../components/Button'
import GitHub from '../components/Icons/Github'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devter🦅</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <AppLayout>
          <section>
            <img src='/Logo.png' alt='Logo' />
            <h1 className={styles.title}>Devter</h1>
            <h2>Talk about development with developers 👨‍💻👩‍💻</h2>
            <div>
              <Button>
                <GitHub width={32} height={32} fill='#fff'/>
                Login with Github
              </Button>
            </div>
          </section>
        </AppLayout>

      <style jsx>{`
        section {
          display: grid;
          height: 100%;
          place-items: center;
          place-content: center;
        }
        img {
          width: 120px;
        }
        h1 {
          color: ${colors.primary};
          font-weight: 800;
          margin-bottom: 16px;
        }
        h2 {
          color: ${colors.secondary};
          font-size: 18px;
          margin: 0;
        }
        div {
          margin-top: 16px;
        }
      `}</style>
    </div>
  )
}
