import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devter 🦅</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Devter 🦅
        </h1>
        <nav>
          <Link href='/timeline'>
            Timeline
          </Link>
        </nav>
      </main>

      <style jsx>{`
        nav {
          font-size: 24px;
          text-align: center;
        }
      `}</style>
    </div>
  )
}
